python /home/young/liuyixin/CAMC_disllter/amc.py \
--arch resnet56_cifar /home/dataset/cifar \
--amc-protocol mac-constrained \
--etes 0.075 --amc-ft-epochs 0 \
--amc-prune-pattern channels \
--amc-prune-method fm-reconstruction \
--amc-agent-algo DDPG \
--amc-cfg /home/young/liuyixin/8.31/distiller/examples/auto_compression/amc/auto_compression_channels.yaml \
--amc-rllib hanlab -j 1 \
--conditional \
--support-ratio 0.5 